vet_clinic_backend/apps/lk/urls.py
from django.urls import path

from . import views

app_name = 'lk'

urlpatterns = [
    path('', views.client_visits, name = 'client_visits'),
    path('visit/<int:id_visit>/', views.client_visit_card, name = 'client_visit_card'),
    path('visit/<int:id_visit>/edit', views.client_visit_card_edit, name = 'client_visit_card_edit'),
    path('pets/new', views.client_pet_create, name = 'client_pet_create'),
    path('pets/', views.client_pets, name = 'client_pets'),
    path('pets/<int:id_pet>/edit/', views.client_pet_edit, name = 'client_pet_edit'),
    path('profile/', views.client_profile, name = 'client_profile'),
    path('history/<int:id_pet>/', views.client_history, name = 'client_history'),
]

vet_clinic_backend/apps/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name = 'index'),
    # path('<str:category>/', views.client_category, name = 'client_category'),
    # path('<int:id_direction>/<int:id>/', views.client_detail, name = 'client_detail'),
    # path('adm', views.index, name = 'index'),
    # path('adm/new_service', views.create, name = 'create'),
    # path('adm/<int:id_direction>/', views.category, name = 'category'),
    # path('adm/<int:id_direction>/<int:id>/', views.detail, name = 'detail'),
]

vet_clinic_backend/apps/reviews/urls.py
from django.urls import path

from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.client_list, name = 'client_list'),
    path('new/', views.client_create, name = 'client_create'),
    path('success/', views.client_message, name = 'client_message'),
    path('<int:category>/', views.client_category, name = 'client_category'),
    path('<int:category>/<int:id>/', views.client_detail, name = 'client_detail'),
]

vet_clinic_backend/apps/sales/urls.py
from django.urls import path

from . import views

app_name = 'sales'

urlpatterns = [
    path('', views.client_list, name = 'client_list'),
    path('<int:id_sale>/', views.client_sale, name = 'client_sale'),
    # path('<str:category>/', views.client_category, name = 'client_category'),
    # path('adm', views.index, name = 'index'),
    # path('adm/new_service', views.create, name = 'create'),
    # path('adm/<int:id_direction>/', views.category, name = 'category'),
    # path('adm/<int:id_direction>/<int:id>/', views.detail, name = 'detail'),
]

vet_clinic_backend/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from users import views as user_views

urlpatterns = [
    path('visits/', include('visits.urls')),
    path('clients/', include('clients.urls')),
    path('filials/', include('filials.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('lk/', include('lk.urls')),
    path('register/', user_views.register, name='register'),
    path('', include('main.urls')),
    path('sales/', include('sales.urls')),
    path('reviews/', include('reviews.urls')),
    path('workers/', include('workers.urls')),
    path('services/', include('services.urls')),
    path('admin/', admin.site.urls)
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

vet_clinic_backend/apps/lk/models.py
from django.db import models

vet_clinic_backend/apps/main/models.py
from django.db import models

# Create your models here.

vet_clinic_backend/apps/users/models.py
from django.db import models

# Create your models here.

vet_clinic_backend/apps/lk/forms.py
from django import forms
# from django.core.exceptions import ValidationError
from clients.models import Pet
from visits.models import Visit

class PetForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = ['name', 'kind', 'date_of_birth']

        widgets = {
            'name': forms.TextInput(),
            'kind':forms.Select(),
            'date_of_birth':forms.DateInput()

        }

class ClientForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = ['name', 'kind', 'date_of_birth']

        widgets = {
            'name': forms.TextInput(),
            'kind':forms.Select(),
            'date_of_birth':forms.DateInput()

        }

class DocCommentForm(forms.ModelForm):
    class Meta:
        model = Visit
        fields = ['comment']

        widgets = {
            'comment': forms.Textarea(attrs={'rows':10, 'style':"width:100%"})
        }

vet_clinic_backend/apps/services/forms.py
from django import forms

from .models import *

class ServiceForm(forms.ModelForm):

    class Meta:
        model = Service
        fields = ('name','description')

vet_clinic_backend/apps/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    # email = forms.EmailField()

    class Meta:
        model = User
        # fields = ['username', 'email', 'password1', 'password2']
        fields = ['username', 'password1', 'password2']

vet_clinic_backend/apps/clients/views.py
from django.http import HttpResponseRedirect
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from .models import *
from visits.models import Visit
from django.contrib.auth.models import User
from django.core.paginator import Paginator

def adm_list(request):
    if request.user.is_authenticated:
        if not request.user.groups.filter(name='managers').exists():
            raise PermissionDenied

    else:
        return HttpResponseRedirect('/accounts/login')
    clients = Client.objects.all().order_by('id')
    pets_all = Pet.objects.filter(date_of_delete = None)
    visits_all = Visit.objects.all()
    paginator = Paginator(clients, 4)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        clients_all = paginator.page(page)
    except(EmptyPage, InvalidPage):
        clients_all = paginator.page(paginator.num_pages)



    return render(request, 'clients/adm-clients.html', {'clients_all':clients_all, 'pets_all':pets_all, 'visits_all':visits_all})


    

vet_clinic_backend/apps/filials/views.py
from django.shortcuts import render, redirect
from reviews.forms import FeedbackForm

def client_contacts(request):
    if request.method == "POST":
        form = FeedbackForm(request.POST)
        if form.is_valid():
            new_review = form.save()
            return redirect('filials:client_message')
        else:
            return render(request, 'filials/contacts.html', {'form':form})
    else:
        form = FeedbackForm()

    return render(request, 'filials/contacts.html', {'form':form})

def client_message(request):
    return render(request, 'filials/success_message.html', {})

vet_clinic_backend/apps/lk/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.db.models import Q
import datetime
from django.utils import timezone
from django.utils.timezone import utc

from .forms import PetForm, DocCommentForm

from django.core.exceptions import PermissionDenied

from django.contrib.auth.models import User

from clients.models import *
from visits.models import Visit
from workers.models import Worker
from services.models import Service
from filials.models import *


from django.core.serializers.json import DjangoJSONEncoder

import datetime
import time
from datetime import timedelta


def client_visits(request):
    lk = ''
    if request.user.is_authenticated:
        try: 
            worker = Worker.objects.get(user=request.user)
            lk = 'worker'
        except:
            try: 
                client = Client.objects.get(user=request.user)
                lk = 'client'
            except:
                return HttpResponseRedirect('/accounts/login')
    else:
        return HttpResponseRedirect('/accounts/login')
    
    if lk == 'client':
        visits_all = Visit.objects.filter(client__id=client.id).order_by('-date')
        visits_active = visits_all.filter(date__gte=datetime.date.today(), date_of_delete=None)
        visits_history_all = []
        for visit in visits_all:
            if visit not in visits_active:
                visits_history_all.append(visit)
        #Фильтры
        doctors_filter = []
        service_filter = []
        for visit in visits_history_all:
            if visit.doctor not in doctors_filter:
                doctors_filter.append(visit.doctor)

            if visit.services != None:
                for service in visit.services.all():
                    if service not in service_filter:
                        service_filter.append(service)

            if visit.sale != None:
                for service in visit.sale.services.all():
                    if service not in service_filter:
                        service_filter.append(service)
        pets_filter = Pet.objects.filter(client=client)
        #Обработка фильтров
        visits_history_view = []
        search_query = request.GET.get('doctor' )
        if search_query:
            d_f,s_f,p_f,date_from,date_before = 'Все','Все','Все','',''
            visits_history_filter = []
            if request.GET['doctor'] != 'Все':
                d_f = int(request.GET['doctor'])
            if request.GET['service'] != 'Все':
                s_f = int(request.GET['service'])         
            if request.GET['pet'] != 'Все':
                p_f = int(request.GET['pet'])
            if request.GET['date_from'] != '':
                date_from = request.GET['date_from']
            if request.GET['date_before'] != '':
                date_before = request.GET['date_before']

            if d_f != 'Все' and s_f == 'Все' and p_f == 'Все':
                for visit in visits_history_all:
                    if visit.doctor.id == int(d_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit)
            
            elif d_f != 'Все' and s_f == 'Все' and p_f != 'Все':   
                for visit in visits_history_all:
                    if visit.doctor.id == int(d_f) and visit.pet.id == int(p_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit) 
            
            elif d_f != 'Все' and s_f != 'Все' and p_f != 'Все': 
                service = Service.objects.get(id=int(s_f))
                for visit in visits_history_all:
                    if service in visit.services.all() and visit.doctor.id == int(d_f) and visit.pet.id == int(p_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit)
                    if visit.sale:
                        sale = visit.sale
                        for service_in_sale in sale.services.all():
                            if service == service_in_sale and visit.doctor.id == int(d_f) and visit.pet.id == int(p_f) and visit not in visits_history_filter:
                                visits_history_filter.append(visit)
            
            elif d_f != 'Все' and s_f != 'Все' and p_f == 'Все':
                service = Service.objects.get(id=int(s_f))
                for visit in visits_history_all:
                    if service in visit.services.all() and visit.doctor.id == int(d_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit)
                    if visit.sale:
                        sale = visit.sale
                        for service_in_sale in sale.services.all():
                            if service == service_in_sale and visit.doctor.id == int(d_f) and visit not in visits_history_filter:
                                visits_history_filter.append(visit)

            elif d_f == 'Все' and s_f != 'Все' and p_f != 'Все':
                service = Service.objects.get(id=int(s_f))
                for visit in visits_history_all:
                    if service in visit.services.all() and visit.pet.id == int(p_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit)
                    if visit.sale:
                        sale = visit.sale
                        for service_in_sale in sale.services.all():
                            if service == service_in_sale and visit.pet.id == int(p_f) and visit not in visits_history_filter:
                                visits_history_filter.append(visit)

            elif d_f == 'Все' and s_f != 'Все' and p_f == 'Все':
                service = Service.objects.get(id=int(s_f))
                for visit in visits_history_all:
                    if service in visit.services.all() and visit not in visits_history_filter:
                        visits_history_filter.append(visit)
                    if visit.sale:
                        sale = visit.sale
                        for service_in_sale in sale.services.all():
                            if service == service_in_sale and visit not in visits_history_filter:
                                visits_history_filter.append(visit)

            elif d_f == 'Все' and s_f == 'Все' and p_f != 'Все':
                for visit in visits_history_all:
                    if visit.pet.id == int(p_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit)

            elif d_f == 'Все' and s_f == 'Все' and p_f == 'Все':
                visits_history_filter = visits_history_all

            for visit in visits_history_filter:
                date1 = visit.date
                if date_from != '' and date_before == '':
                    date2 = datetime.datetime.strptime(date_from, '%Y-%m-%d').replace(tzinfo=utc)
                    if date1 >= date2:
                        visits_history_view.append(visit)

                if date_from != '' and date_before != '':
                    date2 = datetime.datetime.strptime(date_from, '%Y-%m-%d').replace(tzinfo=utc)
                    date3 = datetime.datetime.strptime(date_before, '%Y-%m-%d').replace(tzinfo=utc)
                    if date1 >= date2 and date1 <= date3:
                        visits_history_view.append(visit)

                if date_from == '' and date_before != '':
                    date3 = datetime.datetime.strptime(date_before, '%Y-%m-%d').replace(tzinfo=utc) 
                    if date1 <= date3:
                        visits_history_view.append(visit)

                if date_from == '' and date_before == '':
                    visits_history_view.append(visit)
        else:
            d_f,s_f,p_f,date_from,date_before = 'Все','Все','Все','',''
            visits_history_view = visits_history_all
        #Пагинация
        paginator = Paginator(visits_history_view, 4)
        try:
            page = int(request.GET.get('page', '1'))
        except:
            page = 1
        try:
            visits_history = paginator.page(page)
        except(EmptyPage, InvalidPage):
            visits_history = paginator.page(paginator.num_pages)
        return render(request, 'lk/lk-visits.html', {'visits_all':visits_all, 'client':client, 'visits_active':visits_active, 'visits_history':visits_history, 'doctors_filter':doctors_filter, 'service_filter':service_filter, 'pets_filter':pets_filter, 'd_f':d_f, 's_f':s_f, 'p_f':p_f, 'date_from':date_from ,'date_before':date_before})
    elif lk == 'worker':
        visits_all = Visit.objects.filter(doctor=worker, date_of_delete=None)
        services_all = []
        clients_all = []
        for visit in visits_all:
            if visit.services != None:
                for service in visit.services.all():
                    if service not in services_all:
                        services_all.append(service)

            if visit.sale != None:
                for service in visit.sale.services.all():
                    if service not in services_all:
                        services_all.append(service)
            
            if visit.client != None and visit.client not in clients_all:
                clients_all.append(visit.client)

        visits_planer = []
        
        data = '['
        visits = list(visits_all)
        for visit in visits_all:
            serv = ''
            for service in visit.services.all():
                serv += str(service.name) + ', '

            data += '{"id":' + str(visit.id) + ','
            data += '"name":"' + serv + '",'
            data += '"from":' + str(time.mktime(visit.date.timetuple()) * 1000) + ','
            data += '"duration":' + str(visit.duration)
            if visits.index(visit) + 1 ==  len(visits_all):

                data += '}'
            else:
                data += '},'
        data += ']'

vet_clinic_backend/apps/main/views.py
# from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from services.models import Direction
from sales.models import Sale
from workers.models import Worker
def index(request):
    direction_list = Direction.objects.filter(date_of_delete=None)[:10]
    sale_list = Sale.objects.filter(date_of_delete=None).filter(visibility=True)[:10]
    doctors_list = Worker.objects.filter(date_of_delete=None).filter(visibility=True)[:10]

    return render(request, 'main/index.html', {'direction_list':direction_list, 'sale_list':sale_list, 'doctors_list':doctors_list})

vet_clinic_backend/templates/reviews/add_review.html
{% extends 'base-not-sub-menu.html' %}

{% load static %}

{% block title %}Добавить отзыв{% endblock %}

{% block content %}
<div class="content-title no-sub-menu">
    <div class="content-title__crumbs">
        <a href="{% url 'main:index'%}" class="content-title__link">
            <span>Главная</span>
        </a>
        <svg class="content-title__img">
            <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
        </svg>
        <a href="{% url 'reviews:client_list' %}" class="content-title__link">
            <span>Отзывы</span>
        </a>
        <svg class="content-title__img">
            <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
        </svg>
        <span class="content-title__text">Добавить отзыв</span>
    </div>
    <h1 class="content-title__title">Добавить отзыв</h1>
</div>
<div class="review-form">
    <form method="POST">
        {% csrf_token %}
        <label for="name">Имя</label>
        {% if client != '' %}
        <input type="text" id="name" name="name" value="{{ client.name }}" readonly>
        {% else %}
        <input type="text" id="name" name="name">
        {% endif %}
        <label for="mail">Почта</label>
        {% if client != '' %}
        <input type="email" id="mail" name="mail" value="{{ client.mail }}" required>
        {% else %}
        <input type="email" id="mail" name="mail" required>
        {% endif %}
        <label for="tel">Телефон</label>
        {% if client != '' %}
        <input type="tel" id="tel" name="tel" value="{{ client.phone }}">
        {% else %}
        <input type="tel" id="tel" name="tel">
        {% endif %}
        <label for="rbs">О чем Ваш отзыв?</label>
        <div class="review-form__row r-radio">
            <label for="rb1" style="margin-bottom: 5px;">
                <input type="radio" id="rb1" class="radio" name="review" value="1" checked>
                отзыв о враче</label>
            <label for="rb2">
                <input type="radio" id="rb2" class="radio" name="review" value="2">
                отзыв об услуге</label>
        </div>
        <label>Выберите из списка:</label>
        <select name="doctors" id="select1" data-show-by="rb1">
            {% for doctor in doctors_list %}
            <option value="{{doctor.id}}">{{doctor.surname}} {{doctor.name}} {{doctor.patronymic}}</option>
            {% endfor %}
        </select>
        <select name="services" id="select2" data-show-by="rb2">
            {% for service in services_list %}
            <option value="{{service.id}}">{{service.name}}</option>
            {% endfor %}
        </select>
        <label for="">Отзыв</label>
        <div class="review-form__stars">
            <div class="rating">
                <input class="star" type="radio" name="star" aria-label="5" value="5">
                <input class="star" type="radio" name="star" aria-label="4" value="4">
                <input class="star" type="radio" name="star" aria-label="3" value="3">
                <input class="star" type="radio" name="star" aria-label="2" value="2">
                <input class="star" type="radio" name="star" aria-label="1" value="1" checked>
            </div>
        </div>
        {{ form.content }}
        <button type="submit">Оптравить</button>
    </form>
</div>


{% endblock %}

{% block js %}
<script src="{% static './add_review.js' %}"></script>
{% endblock %}

vet_clinic_backend/templates/reviews/reviews.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Отзывы{% endblock %}

{% block sub-menu__title%}
    <h2>Категории</h2>
{% endblock %}

{% block left-menu %}
    {% if direction_active == 0 %}
        <a href="{% url 'reviews:client_list' %}" class="sub-menu__link">
            <span class="sub-menu__active">Все</span>
            <svg class="sub-menu__img sub-menu__active">
                <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
            </svg>
        </a>
    {% else %}
        <a href="{% url 'reviews:client_list' %}" class="sub-menu__link">
            <span>Все</span>
            <svg class="sub-menu__img">
                <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
            </svg>
        </a>
    {% endif %}
    {% if directions_list %}
        {% for direction in directions_list %}
        {% if direction == 'Услуги' %}
            <a href="{% url 'reviews:client_category' 1 %}" class="sub-menu__link">
            {% else %}    
                <a href="{% url 'reviews:client_category' 2 %}" class="sub-menu__link">
            {% endif %} 
                
                {% if direction == direction_active %}
                    <span class="sub-menu__active">{{ direction }}</span>
                    <svg class="sub-menu__img sub-menu__active">
                        <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
                    </svg>
                {% else %}
                    <span>{{ direction }}</span>
                    <svg class="sub-menu__img">
                        <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
                    </svg>
                {% endif %}
            </a>
        {% endfor %}
    {% else %} категории не найдены
    {% endif %}
{% endblock %}

{% block content %}
    <div class="content-title">
        <div class="content-title__crumbs">
            <a href="{% url 'main:index'%}" class="content-title__link">
                <span>Главная</span>
            </a>
            <svg class="content-title__img">
                <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
            </svg>
            {% if direction_active == 0%}
                <span class="content-title__text">Отзывы: Все</span>
            {% else %}
                <span class="content-title__text">Отзывы: {{direction_active}}</span>
            {% endif %}
        </div>
        <h1 class="content-title__title">Отзывы</h1>
        <div class="m-sub-menu">
            <button class="m-sub-menu__btn">Все категории</button>
        </div>
    </div>
    <section class="search-row">
        <form class="search btn-in-search" action="{% url 'reviews:client_list' %}">
            <div class="search__img">
                <label class="search__label" for="search">
                    <svg>
                        <use href="{% static '' %}images/icons.svg#i-search"></use>
                    </svg>
                </label>
            </div>
            <input name="search" id="search" class="search__input" type="text" placeholder="найти отзыв">
            <button type="submit" class="search__button">
                <svg class="search__button">
                    <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
                </svg>
            </button>
        </form>
        <div class="search-row__btn">
            <a href="{% url 'reviews:client_create' %}" class="btn__min-yellow">Написать отзыв</a>
        </div>
    </section>
    <section class="card-reviews">
        <div class="card-reviews__list">
            {% if reviews_list %}
                {% for review in reviews_list.object_list %}     
                    <div class="card-reviews__item">
                        <div class="card-reviews__client">
                            <div class="card-reviews__col-1">
                                {% if review.client.photo %}
                                <img src="{{ review.client.photo.url }}" alt="">
                                {% else %}
                                <svg class="content-title__img">
                                    <use href="{% static '' %}images/icons.svg#i-user"></use>
                                </svg>
                                {% endif %}
                            </div>
                            <div class="card-reviews__col-2">
                                <div class="card-reviews__stars">
                                        {% for i in 'x'|rjust:review.star %}
                                            <svg>
                                                <use href="{% static '' %}images/icons.svg#i-star-full"></use>
                                            </svg>
                                        {% endfor %}
                                        {% if review.star == 4 %}
                                            <svg>
                                                <use href="{% static '' %}images/icons.svg#i-star-empty"></use>
                                            </svg>
                                        {% elif review.star == 3 %}
                                            <svg>
                                                <use href="{% static '' %}images/icons.svg#i-star-empty"></use>
                                            </svg>
                                            <svg>
                                                    <use href="{% static '' %}images/icons.svg#i-star-empty"></use>
                                            </svg>
                                        {% elif review.star == 2 %}
                                            <svg>
                                                <use href="{% static '' %}images/icons.svg#i-star-empty"></use>
                                            </svg>
                                            <svg>
                                                    <use href="{% static '' %}images/icons.svg#i-star-empty"></use>
                                            </svg>
                                            <svg>
                                                    <use href="{% static '' %}images/icons.svg#i-star-empty"></use>
                                            </svg>
                                        {% elif review.star == 1 %}
                                            <svg>
                                                <use href="{% static '' %}images/icons.svg#i-star-empty"></use>
                                            </svg>
                                            <svg>
                                                    <use href="{% static '' %}images/icons.svg#i-star-empty"></use>
                                            </svg>
                                            <svg>
                                                    <use href="{% static '' %}images/icons.svg#i-star-empty"></use>
                                            </svg>
                                            <svg>
                                                    <use href="{% static '' %}images/icons.svg#i-star-empty"></use>
                                            </svg>
                                        {% endif %}
                                </div>
                                <span class="card-reviews__name">{{review.date}}</span>
                                {% if review.client %}
                                <span class="card-reviews__name">{{review.client.surname}} {{review.client.name}} {{review.client.patronymic}}</span>
                                {% else %}
                                <span class="card-reviews__name">{{review.name}}</span>
                                {% endif %}
                            </div>
                        </div>
                        <div class="card-reviews__review-content">
                            <span>Отзыв</span>
                            {% if review.service != None %}
                                <span>Услуга: {{ review.service.name }}</span>
                            {% endif %}
                            {% if review.doctor != None %}
                                <span>Врач: {{review.doctor.surname}} {{review.doctor.name}} {{review.doctor.patronymic}}</span>
                            {% endif %}

                            <div class="card-reviews__input cropping">
                                <div class="card-reviews__review-text">{{review.content}}</div>
                            </div>
                            {% if review.comment %}
                                <span>Комментарий</span>
                                <div class="card-reviews__input cropping">
                                    <div class="card-reviews__comment-text">{{review.comment}}</div>
                                </div>
                            {% endif %}
                            <div class="card-reviews__button">
                                {% if direction_active == 0 %}
                                <a class="btn__min-yellow" href="{% url 'reviews:client_detail' 0 review.id %}">Подробнее</a>
                                {% elif direction_active == 'Услуги' %}
                                <a class="btn__min-yellow" href="{% url 'reviews:client_detail' 1 review.id %}">Подробнее</a>
                                {% elif direction_active == 'Врачи' %}
                                <a class="btn__min-yellow" href="{% url 'reviews:client_detail' 2 review.id %}">Подробнее</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %} отзывы не найдены
            {% endif %}
        </div>
    </section>
    <section class="pagination">
        {% if reviews_list.has_previous %}
            <a href="?page={{ reviews_list.previous_page_number }}">«</a>
        {% endif %}
        {% for pg in reviews_list.paginator.page_range %}
            {% if reviews_list.number == pg %}
                <a href="?page={{ pg }}" class="pagination__active">{{ pg }}</a>
            {% else %}
                <a href="?page={{ pg }}">{{ pg }}</a>
            {% endif %}
        {% endfor %}
        {% if reviews_list.has_next %}
            <a href="?page={{ reviews_list.next_page_number }}">»</a>
        {% endif %}
    </section>

{% endblock %}