vet_clinic_backend/apps/clients/urls.py
from django.urls import path

from . import views

app_name = 'clients'
urlpatterns = [
    path('', views.adm_list, name = 'adm_list'),
    # path('<int:id_direction>/', views.client_category, name = 'client_category'),
    # path('<int:id_direction>/<int:id>/', views.client_detail, name = 'client_detail'),
    # path('adm', views.index, name = 'index'),
    # path('adm/new_service', views.create, name = 'create'),
    # path('adm/<int:id_direction>/', views.category, name = 'category'),
    # path('adm/<int:id_direction>/<int:id>/', views.detail, name = 'detail'),
]

vet_clinic_backend/apps/filials/urls.py
from django.urls import path

from . import views

app_name = 'filials'

urlpatterns = [
    path('contacts/', views.client_contacts, name = 'client_contacts'),
    path('success/', views.client_message, name = 'client_message'),
    # path('<int:id_direction>/', views.client_category, name = 'client_category'),
    # path('<int:id_direction>/<int:id>/', views.client_detail, name = 'client_detail'),
    # path('adm', views.index, name = 'index'),
    # path('adm/new_service', views.create, name = 'create'),
    # path('adm/<int:id_direction>/', views.category, name = 'category'),
    # path('adm/<int:id_direction>/<int:id>/', views.detail, name = 'detail'),
]

vet_clinic_backend/apps/lk/urls.py
from django.urls import path

from . import views

app_name = 'lk'

urlpatterns = [
    path('', views.client_visits, name = 'client_visits'),
    path('visit/<int:id_visit>/', views.client_visit_card, name = 'client_visit_card'),
    path('visit/<int:id_visit>/edit', views.client_visit_card_edit, name = 'client_visit_card_edit'),
    path('pets/new', views.client_pet_create, name = 'client_pet_create'),
    path('pets/', views.client_pets, name = 'client_pets'),
    path('pets/<int:id_pet>/edit/', views.client_pet_edit, name = 'client_pet_edit'),
    path('profile/', views.client_profile, name = 'client_profile'),
    path('history/<int:id_pet>/', views.client_history, name = 'client_history'),
]

vet_clinic_backend/apps/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name = 'index'),
    # path('<str:category>/', views.client_category, name = 'client_category'),
    # path('<int:id_direction>/<int:id>/', views.client_detail, name = 'client_detail'),
    # path('adm', views.index, name = 'index'),
    # path('adm/new_service', views.create, name = 'create'),
    # path('adm/<int:id_direction>/', views.category, name = 'category'),
    # path('adm/<int:id_direction>/<int:id>/', views.detail, name = 'detail'),
]

vet_clinic_backend/apps/reviews/urls.py
from django.urls import path

from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.client_list, name = 'client_list'),
    path('new/', views.client_create, name = 'client_create'),
    path('success/', views.client_message, name = 'client_message'),
    path('<int:category>/', views.client_category, name = 'client_category'),
    path('<int:category>/<int:id>/', views.client_detail, name = 'client_detail'),
]

vet_clinic_backend/apps/sales/urls.py
from django.urls import path

from . import views

app_name = 'sales'

urlpatterns = [
    path('', views.client_list, name = 'client_list'),
    path('<int:id_sale>/', views.client_sale, name = 'client_sale'),
    # path('<str:category>/', views.client_category, name = 'client_category'),
    # path('adm', views.index, name = 'index'),
    # path('adm/new_service', views.create, name = 'create'),
    # path('adm/<int:id_direction>/', views.category, name = 'category'),
    # path('adm/<int:id_direction>/<int:id>/', views.detail, name = 'detail'),
]

vet_clinic_backend/apps/visits/urls.py
from django.urls import path

from . import views

app_name = 'visits'
urlpatterns = [
    path('', views.adm_list, name = 'adm_list'),
    path('appoitment/', views.client_app, name = 'client_app'),
    path('success/', views.client_message, name = 'client_message'),
    path('<int:id_visit>/', views.adm_detail, name = 'adm_detail'),
    # path('<int:id_direction>/<int:id>/', views.client_detail, name = 'client_detail'),
    # path('adm', views.index, name = 'index'),
    # path('adm/new_service', views.create, name = 'create'),
    # path('adm/<int:id_direction>/', views.category, name = 'category'),
    # path('adm/<int:id_direction>/<int:id>/', views.detail, name = 'detail'),
]

vet_clinic_backend/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from users import views as user_views

urlpatterns = [
    path('visits/', include('visits.urls')),
    path('clients/', include('clients.urls')),
    path('filials/', include('filials.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('lk/', include('lk.urls')),
    path('register/', user_views.register, name='register'),
    path('', include('main.urls')),
    path('sales/', include('sales.urls')),
    path('reviews/', include('reviews.urls')),
    path('workers/', include('workers.urls')),
    path('services/', include('services.urls')),
    path('admin/', admin.site.urls)
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

vet_clinic_backend/apps/services/forms.py
from django import forms

from .models import *

class ServiceForm(forms.ModelForm):

    class Meta:
        model = Service
        fields = ('name','description')

vet_clinic_backend/apps/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    # email = forms.EmailField()

    class Meta:
        model = User
        # fields = ['username', 'email', 'password1', 'password2']
        fields = ['username', 'password1', 'password2']

vet_clinic_backend/apps/clients/views.py
from django.http import HttpResponseRedirect
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from .models import *
from visits.models import Visit
from django.contrib.auth.models import User
from django.core.paginator import Paginator

def adm_list(request):
    if request.user.is_authenticated:
        if not request.user.groups.filter(name='managers').exists():
            raise PermissionDenied

    else:
        return HttpResponseRedirect('/accounts/login')
    clients = Client.objects.all().order_by('id')
    pets_all = Pet.objects.filter(date_of_delete = None)
    visits_all = Visit.objects.all()
    paginator = Paginator(clients, 4)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        clients_all = paginator.page(page)
    except(EmptyPage, InvalidPage):
        clients_all = paginator.page(paginator.num_pages)



    return render(request, 'clients/adm-clients.html', {'clients_all':clients_all, 'pets_all':pets_all, 'visits_all':visits_all})


    

vet_clinic_backend/apps/filials/views.py
from django.shortcuts import render, redirect
from reviews.forms import FeedbackForm

def client_contacts(request):
    if request.method == "POST":
        form = FeedbackForm(request.POST)
        if form.is_valid():
            new_review = form.save()
            return redirect('filials:client_message')
        else:
            return render(request, 'filials/contacts.html', {'form':form})
    else:
        form = FeedbackForm()

    return render(request, 'filials/contacts.html', {'form':form})

def client_message(request):
    return render(request, 'filials/success_message.html', {})

vet_clinic_backend/apps/lk/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.db.models import Q
import datetime
from django.utils import timezone
from django.utils.timezone import utc

from .forms import PetForm, DocCommentForm

from django.core.exceptions import PermissionDenied

from django.contrib.auth.models import User

from clients.models import *
from visits.models import Visit
from workers.models import Worker
from services.models import Service
from filials.models import *


from django.core.serializers.json import DjangoJSONEncoder

import datetime
import time
from datetime import timedelta


def client_visits(request):
    lk = ''
    if request.user.is_authenticated:
        try: 
            worker = Worker.objects.get(user=request.user)
            lk = 'worker'
        except:
            try: 
                client = Client.objects.get(user=request.user)
                lk = 'client'
            except:
                return HttpResponseRedirect('/accounts/login')
    else:
        return HttpResponseRedirect('/accounts/login')
    
    if lk == 'client':
        visits_all = Visit.objects.filter(client__id=client.id).order_by('-date')
        visits_active = visits_all.filter(date__gte=datetime.date.today(), date_of_delete=None)
        visits_history_all = []
        for visit in visits_all:
            if visit not in visits_active:
                visits_history_all.append(visit)
        #Фильтры
        doctors_filter = []
        service_filter = []
        for visit in visits_history_all:
            if visit.doctor not in doctors_filter:
                doctors_filter.append(visit.doctor)

            if visit.services != None:
                for service in visit.services.all():
                    if service not in service_filter:
                        service_filter.append(service)

            if visit.sale != None:
                for service in visit.sale.services.all():
                    if service not in service_filter:
                        service_filter.append(service)
        pets_filter = Pet.objects.filter(client=client)
        #Обработка фильтров
        visits_history_view = []
        search_query = request.GET.get('doctor' )
        if search_query:
            d_f,s_f,p_f,date_from,date_before = 'Все','Все','Все','',''
            visits_history_filter = []
            if request.GET['doctor'] != 'Все':
                d_f = int(request.GET['doctor'])
            if request.GET['service'] != 'Все':
                s_f = int(request.GET['service'])         
            if request.GET['pet'] != 'Все':
                p_f = int(request.GET['pet'])
            if request.GET['date_from'] != '':
                date_from = request.GET['date_from']
            if request.GET['date_before'] != '':
                date_before = request.GET['date_before']

            if d_f != 'Все' and s_f == 'Все' and p_f == 'Все':
                for visit in visits_history_all:
                    if visit.doctor.id == int(d_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit)
            
            elif d_f != 'Все' and s_f == 'Все' and p_f != 'Все':   
                for visit in visits_history_all:
                    if visit.doctor.id == int(d_f) and visit.pet.id == int(p_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit) 
            
            elif d_f != 'Все' and s_f != 'Все' and p_f != 'Все': 
                service = Service.objects.get(id=int(s_f))
                for visit in visits_history_all:
                    if service in visit.services.all() and visit.doctor.id == int(d_f) and visit.pet.id == int(p_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit)
                    if visit.sale:
                        sale = visit.sale
                        for service_in_sale in sale.services.all():
                            if service == service_in_sale and visit.doctor.id == int(d_f) and visit.pet.id == int(p_f) and visit not in visits_history_filter:
                                visits_history_filter.append(visit)
            
            elif d_f != 'Все' and s_f != 'Все' and p_f == 'Все':
                service = Service.objects.get(id=int(s_f))
                for visit in visits_history_all:
                    if service in visit.services.all() and visit.doctor.id == int(d_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit)
                    if visit.sale:
                        sale = visit.sale
                        for service_in_sale in sale.services.all():
                            if service == service_in_sale and visit.doctor.id == int(d_f) and visit not in visits_history_filter:
                                visits_history_filter.append(visit)

            elif d_f == 'Все' and s_f != 'Все' and p_f != 'Все':
                service = Service.objects.get(id=int(s_f))
                for visit in visits_history_all:
                    if service in visit.services.all() and visit.pet.id == int(p_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit)
                    if visit.sale:
                        sale = visit.sale
                        for service_in_sale in sale.services.all():
                            if service == service_in_sale and visit.pet.id == int(p_f) and visit not in visits_history_filter:
                                visits_history_filter.append(visit)

            elif d_f == 'Все' and s_f != 'Все' and p_f == 'Все':
                service = Service.objects.get(id=int(s_f))
                for visit in visits_history_all:
                    if service in visit.services.all() and visit not in visits_history_filter:
                        visits_history_filter.append(visit)
                    if visit.sale:
                        sale = visit.sale
                        for service_in_sale in sale.services.all():
                            if service == service_in_sale and visit not in visits_history_filter:
                                visits_history_filter.append(visit)

            elif d_f == 'Все' and s_f == 'Все' and p_f != 'Все':
                for visit in visits_history_all:
                    if visit.pet.id == int(p_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit)

            elif d_f == 'Все' and s_f == 'Все' and p_f == 'Все':
                visits_history_filter = visits_history_all

            for visit in visits_history_filter:
                date1 = visit.date
                if date_from != '' and date_before == '':
                    date2 = datetime.datetime.strptime(date_from, '%Y-%m-%d').replace(tzinfo=utc)
                    if date1 >= date2:
                        visits_history_view.append(visit)

                if date_from != '' and date_before != '':
                    date2 = datetime.datetime.strptime(date_from, '%Y-%m-%d').replace(tzinfo=utc)
                    date3 = datetime.datetime.strptime(date_before, '%Y-%m-%d').replace(tzinfo=utc)
                    if date1 >= date2 and date1 <= date3:
                        visits_history_view.append(visit)

                if date_from == '' and date_before != '':
                    date3 = datetime.datetime.strptime(date_before, '%Y-%m-%d').replace(tzinfo=utc) 
                    if date1 <= date3:
                        visits_history_view.append(visit)

                if date_from == '' and date_before == '':
                    visits_history_view.append(visit)
        else:
            d_f,s_f,p_f,date_from,date_before = 'Все','Все','Все','',''
            visits_history_view = visits_history_all
        #Пагинация
        paginator = Paginator(visits_history_view, 4)
        try:
            page = int(request.GET.get('page', '1'))
        except:
            page = 1
        try:
            visits_history = paginator.page(page)
        except(EmptyPage, InvalidPage):
            visits_history = paginator.page(paginator.num_pages)
        return render(request, 'lk/lk-visits.html', {'visits_all':visits_all, 'client':client, 'visits_active':visits_active, 'visits_history':visits_history, 'doctors_filter':doctors_filter, 'service_filter':service_filter, 'pets_filter':pets_filter, 'd_f':d_f, 's_f':s_f, 'p_f':p_f, 'date_from':date_from ,'date_before':date_before})
    elif lk == 'worker':
        visits_all = Visit.objects.filter(doctor=worker, date_of_delete=None)
        services_all = []
        clients_all = []
        for visit in visits_all:
            if visit.services != None:
                for service in visit.services.all():
                    if service not in services_all:
                        services_all.append(service)

            if visit.sale != None:
                for service in visit.sale.services.all():
                    if service not in services_all:
                        services_all.append(service)
            
            if visit.client != None and visit.client not in clients_all:
                clients_all.append(visit.client)

        visits_planer = []
        
        data = '['
        visits = list(visits_all)
        for visit in visits_all:
            serv = ''
            for service in visit.services.all():
                serv += str(service.name) + ', '

            data += '{"id":' + str(visit.id) + ','
            data += '"name":"' + serv + '",'
            data += '"from":' + str(time.mktime(visit.date.timetuple()) * 1000) + ','
            data += '"duration":' + str(visit.duration)
            if visits.index(visit) + 1 ==  len(visits_all):

                data += '}'
            else:
                data += '},'
        data += ']'

vet_clinic_backend/templates/base-not-sub-menu.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Ветеринарная клиника{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=PT+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static './styles.css' %}">
</head>

<body>
    <div class="page">
        <div class="page__header">
            <div class="header">
                <div class="header__logo">
                    <img src="{% static './images/logo.svg' %}" alt="Логотип">
                </div>
                <div class="header__rows">
                    <div class="header__row">
                        <div class="header__col header__col--left">
                            <a href="#">
                                <svg class="header__soc">
                                    <use href="{% static '' %}images/icons.svg#i-instagram"></use>
                                </svg>
                            </a>
                            <a href="#">
                                <svg class="header__soc">
                                    <use href="{% static '' %}images/icons.svg#i-vk"></use>
                                </svg>
                            </a>
                            <a class="header__tel" href="tel:+78008888888">+7(800)-888-88-88</a>
                            <div class="header__city">Иркутск</div>
                        </div>
                        <div class="header__col header__col--rigth">
                            <div class="header__menu">
                                <svg class="header__i-menu">
                                    <use href="{% static '' %}images/icons.svg#i-menu"></use>
                                </svg>
                            </div>
                            <div class="header__min-logo">
                                <img class="" src="{% static './images/logo.svg' %}" alt="">
                            </div>
                            <a href="{% url 'lk:client_visits' %}">
                                {% if user.is_authenticated %}
                                <a href="{% url 'lk:client_visits' %}" class="header__city">{{ user.username }}</a>
                                <a href="{% url 'logout' %}" class="btn__max-yellow" style="margin-right: 10px; min-width: 60px; width: 60px">Выйти</a>
                                {% else %}
                                <svg class="header__user">
                                    <use href="{% static '' %}images/icons.svg#i-user"></use>
                                </svg>
                                {% endif %}
                            </a>
                            <a href="#" class="btn__max-orange">Запись на прием</a>
                        </div>
                    </div>
                    <div class="header__row">
                        <div class="main-menu hide">
                            <a href="{% url 'main:index' %}" class="main-menu__link">Главная</a>
                            <a href="{% url 'services:client_list' %}" class="main-menu__link">Услуги</a>
                            <a href="{% url 'workers:client_list' %}" class="main-menu__link">Врачи</a>
                            <a href="{% url 'filials:client_contacts' %}" class="main-menu__link">Контакты</a>
                            <a href="{% url 'reviews:client_list' %}" class="main-menu__link">Отзывы</a>
                            <a href="{% url 'sales:client_list' %}" class="main-menu__link">Акции</a>
                            <a href="{% url 'lk:client_visits' %}" class="main-menu__link last">Личный кабинет</a>
                            <div class="main-menu__mobil-row">
                                <a href="#" class="main-menu__mobil">
                                    <svg class="header__soc">
                                        <use href="./images/icons.svg#i-instagram"></use>
                                    </svg>
                                </a>
                                <a href="#" class="main-menu__mobil">
                                    <svg class="header__soc">
                                        <use href="./images/icons.svg#i-vk"></use>
                                    </svg>
                                </a>
                                <a class="header__tel main-menu__mobil"
                                    href="tel:+78008888888">+7(800)-888-88-88</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="page__body">
            <div class="page__content">
                {% block content %}{% endblock %}
            </div>
        </div>
        <div class="page__footer">
            <div class="footer">
                <div class="footer__logo">
                    <img src="{% static './images/logo.svg' %}" alt="">
                </div>
                <div class="footer__menu">
                    <a href="index.html">Главная</a>
                    <a href="{% url 'services:client_list' %}">Услуги</a>
                    <a href="{% url 'workers:client_list' %}">Врачи</a>
                    <a href="{% url 'filials:client_contacts' %}">Контакты</a>
                    <a href="{% url 'reviews:client_list' %}">Отзывы</a>
                    <a href="{% url 'sales:client_list' %}">Акции</a>
                    <a href="{% url 'lk:client_visits' %}">Личный кабинет</a>
                </div>
                <div class="footer__contacts">
                    <div class="footer__soc">
                        <svg>
                            <use href="{% static '' %}images/icons.svg#i-instagram"></use>
                        </svg>
                        <svg>
                            <use href="{% static '' %}images/icons.svg#i-vk"></use>
                        </svg>
                    </div>
                    <a href="tel:+78008888888">+7(800)-888-88-88</a>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static './scripts.js' %}"></script>
    {% block js %}{% endblock %}
</body>

</html>

vet_clinic_backend/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Ветеринарная клиника{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=PT+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static './styles.css' %}">
</head>

<body>
    <div class="page">
        <div class="page__header">
            <div class="header">
                <a href="{% url 'main:index'%}" class="header__logo">
                    <img src="{% static './images/logo.svg' %}" alt="Логотип">
                </a>
                <div class="header__rows">
                    <div class="header__row">
                        <div class="header__col header__col--left">
                            <a href="#">
                                <svg class="header__soc">
                                    <use href="{% static '' %}images/icons.svg#i-instagram"></use>
                                </svg>
                            </a>
                            <a href="#">
                                <svg class="header__soc">
                                    <use href="{% static '' %}images/icons.svg#i-vk"></use>
                                </svg>
                            </a>
                            <a class="header__tel" href="tel:+78008888888">+7(800)-888-88-88</a>
                            <div class="header__city">Иркутск</div>
                        </div>
                        <div class="header__col header__col--rigth">
                            <div class="header__menu">
                                <svg class="header__i-menu">
                                    <use href="{% static '' %}images/icons.svg#i-menu"></use>
                                </svg>
                            </div>
                            <div class="header__min-logo">
                                <img src="{% static './images/logo.svg' %}" alt="">
                            </div>
                            <a href="{% url 'lk:client_visits' %}">
                                {% if user.is_authenticated %}
                                <a href="{% url 'lk:client_visits' %}" class="header__city">{{ user.username }}</a>
                                <a href="{% url 'logout' %}" class="btn__max-yellow" style="margin-right: 10px; min-width: 60px; width: 60px">Выйти</a>
                                {% else %}
                                <svg class="header__user">
                                    <use href="{% static '' %}images/icons.svg#i-user"></use>
                                </svg>
                                {% endif %}
                            </a>
                            <a href="{% url 'visits:client_app' %}" class="btn__max-orange">Запись на прием</a>
                        </div>
                    </div>
                    <div class="header__row">
                        <div class="main-menu hide">
                            <a href="{% url 'main:index' %}" class="main-menu__link">Главная</a>
                            <a href="{% url 'services:client_list' %}" class="main-menu__link">Услуги</a>
                            <a href="{% url 'workers:client_list' %}" class="main-menu__link">Врачи</a>
                            <a href="{% url 'filials:client_contacts' %}" class="main-menu__link">Контакты</a>
                            <a href="{% url 'reviews:client_list' %}" class="main-menu__link">Отзывы</a>
                            <a href="{% url 'sales:client_list' %}" class="main-menu__link">Акции</a>
                            <a href="{% url 'lk:client_visits' %}" class="main-menu__link last">Личный кабинет</a>
                            <div class="main-menu__mobil-row">
                                <a href="#" class="main-menu__mobil">
                                    <svg class="header__soc">
                                        <use href="./images/icons.svg#i-instagram"></use>
                                    </svg>
                                </a>
                                <a href="#" class="main-menu__mobil">
                                    <svg class="header__soc">
                                        <use href="./images/icons.svg#i-vk"></use>
                                    </svg>
                                </a>
                                <a class="header__tel main-menu__mobil"
                                    href="tel:+78008888888">+7(800)-888-88-88</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="page__body">
            <div class="page__sub-menu hide">
                <div class="sub-menu">
                    <div class="sub-menu__title">
                        {% block sub-menu__title%}{% endblock %}
                        <div class="m-sub-menu__close">
                            <svg>
                                <use href="{% static '' %}images/icons.svg#i-close"></use>
                            </svg>
                        </div>
                    </div>
                    {% block left-menu %}{% endblock %}
                </div>
            </div>
            <div class="page__content">
                {% if messages %}
                {% for message in messages %}
                <div>{{ message }}</div>
                {% endfor %}
                {% endif %}

                {% block content %}{% endblock %}
            </div>
        </div>
        <div class="page__footer">
            <div class="footer">
                <div class="footer__logo">
                    <img src="{% static './images/logo.svg' %}" alt="">
                </div>
                <div class="footer__menu">
                    <a href="index.html">Главная</a>
                    <a href="{% url 'services:client_list' %}">Услуги</a>
                    <a href="{% url 'workers:client_list' %}">Врачи</a>
                    <a href="{% url 'filials:client_contacts' %}">Контакты</a>
                    <a href="{% url 'reviews:client_list' %}">Отзывы</a>
                    <a href="{% url 'sales:client_list' %}">Акции</a>
                    <a href="{% url 'lk:client_visits' %}">Личный кабинет</a>
                </div>
                <div class="footer__contacts">
                    <div class="footer__soc">
                        <svg>
                            <use href="{% static '' %}images/icons.svg#i-instagram"></use>
                        </svg>
                        <svg>
                            <use href="{% static '' %}images/icons.svg#i-vk"></use>
                        </svg>
                    </div>
                    <a href="tel:+78008888888">+7(800)-888-88-88</a>
                </div>
            </div>
        </div>
    </div>
    
    <script src="{% static './scripts.js' %}"></script>
    {% block js %}{% endblock %}
</body>

</html>