vet_clinic_backend/apps/lk/urls.py
from django.urls import path

from . import views

app_name = 'lk'

urlpatterns = [
    path('', views.client_visits, name = 'client_visits'),
    path('visit/<int:id_visit>/', views.client_visit_card, name = 'client_visit_card'),
    path('visit/<int:id_visit>/edit', views.client_visit_card_edit, name = 'client_visit_card_edit'),
    path('pets/new', views.client_pet_create, name = 'client_pet_create'),
    path('pets/', views.client_pets, name = 'client_pets'),
    path('pets/<int:id_pet>/edit/', views.client_pet_edit, name = 'client_pet_edit'),
    path('profile/', views.client_profile, name = 'client_profile'),
    path('history/<int:id_pet>/', views.client_history, name = 'client_history'),
]

vet_clinic_backend/apps/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name = 'index'),
    # path('<str:category>/', views.client_category, name = 'client_category'),
    # path('<int:id_direction>/<int:id>/', views.client_detail, name = 'client_detail'),
    # path('adm', views.index, name = 'index'),
    # path('adm/new_service', views.create, name = 'create'),
    # path('adm/<int:id_direction>/', views.category, name = 'category'),
    # path('adm/<int:id_direction>/<int:id>/', views.detail, name = 'detail'),
]

vet_clinic_backend/apps/sales/urls.py
from django.urls import path

from . import views

app_name = 'sales'

urlpatterns = [
    path('', views.client_list, name = 'client_list'),
    path('<int:id_sale>/', views.client_sale, name = 'client_sale'),
    # path('<str:category>/', views.client_category, name = 'client_category'),
    # path('adm', views.index, name = 'index'),
    # path('adm/new_service', views.create, name = 'create'),
    # path('adm/<int:id_direction>/', views.category, name = 'category'),
    # path('adm/<int:id_direction>/<int:id>/', views.detail, name = 'detail'),
]

vet_clinic_backend/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from users import views as user_views

urlpatterns = [
    path('visits/', include('visits.urls')),
    path('clients/', include('clients.urls')),
    path('filials/', include('filials.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('lk/', include('lk.urls')),
    path('register/', user_views.register, name='register'),
    path('', include('main.urls')),
    path('sales/', include('sales.urls')),
    path('reviews/', include('reviews.urls')),
    path('workers/', include('workers.urls')),
    path('services/', include('services.urls')),
    path('admin/', admin.site.urls)
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

vet_clinic_backend/apps/lk/models.py
from django.db import models

vet_clinic_backend/apps/main/models.py
from django.db import models

# Create your models here.

vet_clinic_backend/apps/lk/forms.py
from django import forms
# from django.core.exceptions import ValidationError
from clients.models import Pet
from visits.models import Visit

class PetForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = ['name', 'kind', 'date_of_birth']

        widgets = {
            'name': forms.TextInput(),
            'kind':forms.Select(),
            'date_of_birth':forms.DateInput()

        }

class ClientForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = ['name', 'kind', 'date_of_birth']

        widgets = {
            'name': forms.TextInput(),
            'kind':forms.Select(),
            'date_of_birth':forms.DateInput()

        }

class DocCommentForm(forms.ModelForm):
    class Meta:
        model = Visit
        fields = ['comment']

        widgets = {
            'comment': forms.Textarea(attrs={'rows':10, 'style':"width:100%"})
        }

vet_clinic_backend/apps/reviews/forms.py
from django import forms
from django.core.exceptions import ValidationError
from reviews.models import *

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['content', 'phone', 'name', 'mail']

        widgets = {
            'content': forms.Textarea(attrs={'cols':30,'rows':10}),
            'phone': forms.TextInput(attrs={'type':'tel','id':'tel'}),
            'name': forms.TextInput(),
            'mail': forms.TextInput(attrs={'type':'email','id':'mail'}),
        }

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['comment', 'phone', 'name', 'mail']

        widgets = {
            'comment': forms.Textarea(attrs={'placeholder':'Комментарий','class':'con-form__comment', 'required':True, 'rows':5}),
            'phone': forms.TextInput(attrs={'placeholder':'Телефон','class':'con-form__tel', 'required':True}),
            'name': forms.TextInput(attrs={'placeholder':'Ваше имя','class':'con-form__tel', 'required':True}),
            'mail': forms.TextInput(attrs={'placeholder':'Почта','class':'con-form__tel','type':'email'})
        }

vet_clinic_backend/apps/services/forms.py
from django import forms

from .models import *

class ServiceForm(forms.ModelForm):

    class Meta:
        model = Service
        fields = ('name','description')

vet_clinic_backend/apps/clients/views.py
from django.http import HttpResponseRedirect
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from .models import *
from visits.models import Visit
from django.contrib.auth.models import User
from django.core.paginator import Paginator

def adm_list(request):
    if request.user.is_authenticated:
        if not request.user.groups.filter(name='managers').exists():
            raise PermissionDenied

    else:
        return HttpResponseRedirect('/accounts/login')
    clients = Client.objects.all().order_by('id')
    pets_all = Pet.objects.filter(date_of_delete = None)
    visits_all = Visit.objects.all()
    paginator = Paginator(clients, 4)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        clients_all = paginator.page(page)
    except(EmptyPage, InvalidPage):
        clients_all = paginator.page(paginator.num_pages)



    return render(request, 'clients/adm-clients.html', {'clients_all':clients_all, 'pets_all':pets_all, 'visits_all':visits_all})


    

vet_clinic_backend/apps/filials/views.py
from django.shortcuts import render, redirect
from reviews.forms import FeedbackForm

def client_contacts(request):
    if request.method == "POST":
        form = FeedbackForm(request.POST)
        if form.is_valid():
            new_review = form.save()
            return redirect('filials:client_message')
        else:
            return render(request, 'filials/contacts.html', {'form':form})
    else:
        form = FeedbackForm()

    return render(request, 'filials/contacts.html', {'form':form})

def client_message(request):
    return render(request, 'filials/success_message.html', {})

vet_clinic_backend/apps/lk/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.db.models import Q
import datetime
from django.utils import timezone
from django.utils.timezone import utc

from .forms import PetForm, DocCommentForm

from django.core.exceptions import PermissionDenied

from django.contrib.auth.models import User

from clients.models import *
from visits.models import Visit
from workers.models import Worker
from services.models import Service
from filials.models import *


from django.core.serializers.json import DjangoJSONEncoder

import datetime
import time
from datetime import timedelta


def client_visits(request):
    lk = ''
    if request.user.is_authenticated:
        try: 
            worker = Worker.objects.get(user=request.user)
            lk = 'worker'
        except:
            try: 
                client = Client.objects.get(user=request.user)
                lk = 'client'
            except:
                return HttpResponseRedirect('/accounts/login')
    else:
        return HttpResponseRedirect('/accounts/login')
    
    if lk == 'client':
        visits_all = Visit.objects.filter(client__id=client.id).order_by('-date')
        visits_active = visits_all.filter(date__gte=datetime.date.today(), date_of_delete=None)
        visits_history_all = []
        for visit in visits_all:
            if visit not in visits_active:
                visits_history_all.append(visit)
        #Фильтры
        doctors_filter = []
        service_filter = []
        for visit in visits_history_all:
            if visit.doctor not in doctors_filter:
                doctors_filter.append(visit.doctor)

            if visit.services != None:
                for service in visit.services.all():
                    if service not in service_filter:
                        service_filter.append(service)

            if visit.sale != None:
                for service in visit.sale.services.all():
                    if service not in service_filter:
                        service_filter.append(service)
        pets_filter = Pet.objects.filter(client=client)
        #Обработка фильтров
        visits_history_view = []
        search_query = request.GET.get('doctor' )
        if search_query:
            d_f,s_f,p_f,date_from,date_before = 'Все','Все','Все','',''
            visits_history_filter = []
            if request.GET['doctor'] != 'Все':
                d_f = int(request.GET['doctor'])
            if request.GET['service'] != 'Все':
                s_f = int(request.GET['service'])         
            if request.GET['pet'] != 'Все':
                p_f = int(request.GET['pet'])
            if request.GET['date_from'] != '':
                date_from = request.GET['date_from']
            if request.GET['date_before'] != '':
                date_before = request.GET['date_before']

            if d_f != 'Все' and s_f == 'Все' and p_f == 'Все':
                for visit in visits_history_all:
                    if visit.doctor.id == int(d_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit)
            
            elif d_f != 'Все' and s_f == 'Все' and p_f != 'Все':   
                for visit in visits_history_all:
                    if visit.doctor.id == int(d_f) and visit.pet.id == int(p_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit) 
            
            elif d_f != 'Все' and s_f != 'Все' and p_f != 'Все': 
                service = Service.objects.get(id=int(s_f))
                for visit in visits_history_all:
                    if service in visit.services.all() and visit.doctor.id == int(d_f) and visit.pet.id == int(p_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit)
                    if visit.sale:
                        sale = visit.sale
                        for service_in_sale in sale.services.all():
                            if service == service_in_sale and visit.doctor.id == int(d_f) and visit.pet.id == int(p_f) and visit not in visits_history_filter:
                                visits_history_filter.append(visit)
            
            elif d_f != 'Все' and s_f != 'Все' and p_f == 'Все':
                service = Service.objects.get(id=int(s_f))
                for visit in visits_history_all:
                    if service in visit.services.all() and visit.doctor.id == int(d_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit)
                    if visit.sale:
                        sale = visit.sale
                        for service_in_sale in sale.services.all():
                            if service == service_in_sale and visit.doctor.id == int(d_f) and visit not in visits_history_filter:
                                visits_history_filter.append(visit)

            elif d_f == 'Все' and s_f != 'Все' and p_f != 'Все':
                service = Service.objects.get(id=int(s_f))
                for visit in visits_history_all:
                    if service in visit.services.all() and visit.pet.id == int(p_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit)
                    if visit.sale:
                        sale = visit.sale
                        for service_in_sale in sale.services.all():
                            if service == service_in_sale and visit.pet.id == int(p_f) and visit not in visits_history_filter:
                                visits_history_filter.append(visit)

            elif d_f == 'Все' and s_f != 'Все' and p_f == 'Все':
                service = Service.objects.get(id=int(s_f))
                for visit in visits_history_all:
                    if service in visit.services.all() and visit not in visits_history_filter:
                        visits_history_filter.append(visit)
                    if visit.sale:
                        sale = visit.sale
                        for service_in_sale in sale.services.all():
                            if service == service_in_sale and visit not in visits_history_filter:
                                visits_history_filter.append(visit)

            elif d_f == 'Все' and s_f == 'Все' and p_f != 'Все':
                for visit in visits_history_all:
                    if visit.pet.id == int(p_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit)

            elif d_f == 'Все' and s_f == 'Все' and p_f == 'Все':
                visits_history_filter = visits_history_all

            for visit in visits_history_filter:
                date1 = visit.date
                if date_from != '' and date_before == '':
                    date2 = datetime.datetime.strptime(date_from, '%Y-%m-%d').replace(tzinfo=utc)
                    if date1 >= date2:
                        visits_history_view.append(visit)

                if date_from != '' and date_before != '':
                    date2 = datetime.datetime.strptime(date_from, '%Y-%m-%d').replace(tzinfo=utc)
                    date3 = datetime.datetime.strptime(date_before, '%Y-%m-%d').replace(tzinfo=utc)
                    if date1 >= date2 and date1 <= date3:
                        visits_history_view.append(visit)

                if date_from == '' and date_before != '':
                    date3 = datetime.datetime.strptime(date_before, '%Y-%m-%d').replace(tzinfo=utc) 
                    if date1 <= date3:
                        visits_history_view.append(visit)

                if date_from == '' and date_before == '':
                    visits_history_view.append(visit)
        else:
            d_f,s_f,p_f,date_from,date_before = 'Все','Все','Все','',''
            visits_history_view = visits_history_all
        #Пагинация
        paginator = Paginator(visits_history_view, 4)
        try:
            page = int(request.GET.get('page', '1'))
        except:
            page = 1
        try:
            visits_history = paginator.page(page)
        except(EmptyPage, InvalidPage):
            visits_history = paginator.page(paginator.num_pages)
        return render(request, 'lk/lk-visits.html', {'visits_all':visits_all, 'client':client, 'visits_active':visits_active, 'visits_history':visits_history, 'doctors_filter':doctors_filter, 'service_filter':service_filter, 'pets_filter':pets_filter, 'd_f':d_f, 's_f':s_f, 'p_f':p_f, 'date_from':date_from ,'date_before':date_before})
    elif lk == 'worker':
        visits_all = Visit.objects.filter(doctor=worker, date_of_delete=None)
        services_all = []
        clients_all = []
        for visit in visits_all:
            if visit.services != None:
                for service in visit.services.all():
                    if service not in services_all:
                        services_all.append(service)

            if visit.sale != None:
                for service in visit.sale.services.all():
                    if service not in services_all:
                        services_all.append(service)
            
            if visit.client != None and visit.client not in clients_all:
                clients_all.append(visit.client)

        visits_planer = []
        
        data = '['
        visits = list(visits_all)
        for visit in visits_all:
            serv = ''
            for service in visit.services.all():
                serv += str(service.name) + ', '

            data += '{"id":' + str(visit.id) + ','
            data += '"name":"' + serv + '",'
            data += '"from":' + str(time.mktime(visit.date.timetuple()) * 1000) + ','
            data += '"duration":' + str(visit.duration)
            if visits.index(visit) + 1 ==  len(visits_all):

                data += '}'
            else:
                data += '},'
        data += ']'

vet_clinic_backend/apps/main/views.py
# from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from services.models import Direction
from sales.models import Sale
from workers.models import Worker
def index(request):
    direction_list = Direction.objects.filter(date_of_delete=None)[:10]
    sale_list = Sale.objects.filter(date_of_delete=None).filter(visibility=True)[:10]
    doctors_list = Worker.objects.filter(date_of_delete=None).filter(visibility=True)[:10]

    return render(request, 'main/index.html', {'direction_list':direction_list, 'sale_list':sale_list, 'doctors_list':doctors_list})

vet_clinic_backend/templates/lk/d-lk-visit-card.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Карточка приема{% endblock %}

{% block sub-menu__title%}
<h2>Личный кабинет</h2>
{% endblock %}

{% block left-menu %}
<a href="{% url 'lk:client_visits' %}" class="sub-menu__link">
    <span class="sub-menu__active">
        Приемы
    </span>
    <svg class="sub-menu__img sub-menu__active">
        <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
    </svg>
</a>
<a href="{% url 'lk:client_pets' %}" class="sub-menu__link">
    <span>
        Расписание
    </span>
    <svg class="sub-menu__img">
        <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
    </svg>
</a>
<a href="{% url 'lk:client_profile' %}" class="sub-menu__link">
    <span>
        Профиль
    </span>
    <svg class="sub-menu__img">
        <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
    </svg>
</a>
{% endblock %}

{% block content %}
<div class="content-title adm">
    <div class="content-title__crumbs">
        <a href="{% url 'main:index'%}" class="content-title__link">
            <span>Главная</span>
        </a>
        <svg class="content-title__img">
            <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
        </svg>
        <a href="{% url 'lk:client_visits' %}" class="content-title__link">
            <span>Личный кабинет - Приемы</span>
        </a>
        <svg class="content-title__img">
            <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
        </svg>
        <span class="content-title__text">Карточка приема</span>
    </div>
    <h1 class="content-title__title">Карточка приема</h1>
</div>
<section class="list-cards">
    <div class="list-cards__item">
        <div class="list-cards__col-1">
            <div class="list-cards__row">
                <div class="key">
                    <span>Питомец:</span>
                </div>
                <div class="value">
                    {% if visit.pet %}
                    <span>{{ visit.pet.kind.value }}</span>
                    {% else %}
                    <span>{{ visit.pet_kind.value }}</span>
                    {% endif %}
                </div>
            </div>
            <div class="list-cards__row">
                <div class="key">
                    <span>Кличка:</span>
                </div>
                <div class="value">
                    {% if visit.pet %}
                    <span>{{ visit.pet.name }}</span>
                    {% else %}
                    <span>{{ visit.pet_name }}</span>
                    {% endif %}
                </div>
            </div>
            <div class="list-cards__row">
                <div class="key">
                    <span>Пол:</span>
                </div>
                <div class="value">
                    {% if visit.pet.sex == True %}
                    <span>Мужской</span>
                    {% else %}
                    <span>Женский</span>
                    {% endif %}
                </div>
            </div>
            <div class="list-cards__row">
                <div class="key">
                    <span>Дата рождения:</span>
                </div>
                <div class="value">
                    <span>{{ visit.pet.date_of_birth }}</span>
                </div>
            </div>
        </div>
        <div class="list-cards__col-2">
            <div class="list-cards__avatar">
                {% if visit.pet.photo %}
                <img src="{{visit.pet.photo.url}}" alt="">
                {% else %}
                <svg style="width: 90px;">
                    <use href="{% static '' %}images/icons.svg#i-foot"></use>
                </svg>
                {% endif %}
            </div>
        </div>
        {% if pet %}
        <!-- <div class="list-cards__btns">
            <a class="btn__min-yellow" href="{% url 'lk:client_history' visit.pet.id %}">История</a>
        </div> -->
        {% endif %}
    </div>
    <div class="list-cards__item">
        <div class="list-cards__col-1">
            <div class="list-cards__row">
                <div class="key">
                    <span>Фамилия:</span>
                </div>
                <div class="value">
                    {% if visit.client %}
                    <span>{{visit.client.surname}}</span>
                    {% else %}
                    <span>-</span>
                    {% endif %}
                </div>
            </div>
            <div class="list-cards__row">
                <div class="key">
                    <span>Имя:</span>
                </div>
                <div class="value">
                    {% if visit.client %}
                    <span>{{visit.client.name}}</span>
                    {% else %}
                    <span>{{visit.name}}</span>
                    {% endif %}
                </div>
            </div>
            <div class="list-cards__row">
                <div class="key">
                    <span>Отчество:</span>
                </div>
                <div class="value">
                    {% if visit.client %}
                    <span>{{visit.client.patronymic}}</span>
                    {% else %}
                    <span>-</span>
                    {% endif %}
                </div>
            </div>
            <div class="list-cards__row">
                <div class="key">
                    <span>Телефон:</span>
                </div>
                <div class="value">
                    {% if visit.client %}
                    <span>{{visit.client.phone}}</span>
                    {% else %}
                    <span>{{visit.phone}}</span>
                    {% endif %}
                </div>
            </div>
            <div class="list-cards__row">
                <div class="key">
                    <span>Почта:</span>
                </div>
                <div class="value">
                    {% if visit.client %}
                    <span>{{visit.client.mail}}</span>
                    {% else %}
                    <span>-</span>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="list-cards__col-2">
            <div class="list-cards__avatar">
                {% if visit.client.photo %}
                <img src="{{visit.client.photo.url}}" alt="">
                {% else %}
                <svg style="width: 85px;">
                    <use href="{% static '' %}images/icons.svg#i-user"></use>
                </svg>
                {% endif %}
            </div>
        </div>
    </div>
</section>
<div class="adm-card__btns" style="margin-bottom: 20px; padding-right: 20px;">
    <!-- <a href="adm-visit-card__edit.html" class="btn__min-orange">Повторить</a> -->
    <!-- <a href="{% url 'lk:client_visit_card_edit' visit.id %}" class="btn__min-orange">Изменить</a> -->
</div>
<section class="lk-his-list">
    <div class="card-visit">
        <div class="card-visit__col-1">
            <div class="card-visit__row">
                <h4>ID:</h4>
                <span>{{ visit.id }}</span>
            </div>
            <div class="card-visit__row">
                <h4>Дата и время:</h4>
                <span>{{ visit.date }}</span>
            </div>
            <div class="card-visit__row">
                <h4>Филиал:</h4>
                <span>{{ visit.filial.address }}</span>
            </div>
            <div class="card-visit__row">
                <h4>Кабинет:</h4>
                <span>{{ visit.cabinet.name }}</span>
            </div>
            <div class="card-visit__row">
                <h4>Питомец:</h4>
                {% if visit.pet %}
                <span>{{ visit.pet.kind.value }}</span>
                {% else %}
                <span>{{ visit.pet_kind.value }}</span>
                {% endif %}
            </div>
            <div class="card-visit__row">
                <h4>Кличка:</h4>
                {% if visit.pet %}
                <span>{{ visit.pet.name }}</span>
                {% else %}
                <span>{{ visit.pet_name }}</span>
                {% endif %}
            </div>
            <div class="card-visit__row">
                <h4>Врач:</h4>
                <span>{{visit.doctor.surname}} {{visit.doctor.name|truncatechars:2}} {{visit.doctor.patronymic|truncatechars:2}}</span>
            </div>
            <div class="card-visit__row">
                <h4>Стоимость:</h4>
                <span>{{ visit.cost }}</span>
            </div>
        </div>
        <div class="card-visit__col-2">
            <h4>Услуга (-и):</h4>
            {% if visit.sale != None %}
            {% for service in visit.sale.services.all %}
            <span>{{ service.name }}</span>
            {% endfor %}
            {% else %}
            {% for service in visit.services.all %}
            <span>{{ service.name }}</span>
            {% endfor %}
            {% endif %}
        </div>
        <form class="card-visit__col-3" method="POST">
            {% csrf_token %}
            <h4>Комментарий от врача</h4>
            {{ form.comment }}
            <button type="submit" class="btn__min-orange">Сохранить и закрыть</button>
        </form>
    </div>
</section>
{% endblock %}

vet_clinic_backend/templates/lk/lk-pets.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Мои питомцы{% endblock %}

{% block sub-menu__title%}
<h2>Личный кабинет</h2>
{% endblock %}

{% block left-menu %}
<a href="{% url 'lk:client_visits' %}" class="sub-menu__link">
    <span>
        Приемы
    </span>
    <svg class="sub-menu__img">
        <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
    </svg>
</a>
<a href="{% url 'lk:client_pets' %}" class="sub-menu__link">
    <span class="sub-menu__active">
        Мои питомцы
    </span>
    <svg class="sub-menu__img sub-menu__active">
        <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
    </svg>
</a>
<a href="{% url 'lk:client_profile' %}" class="sub-menu__link">
    <span>
        Профиль
    </span>
    <svg class="sub-menu__img">
        <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
    </svg>
</a>
{% endblock %}

{% block content %}
<div class="content-title">
    <div class="content-title__crumbs">
        <a href="{% url 'main:index'%}" class="content-title__link">
            <span>Главная</span>
        </a>
        <svg class="content-title__img">
            <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
        </svg>
        <span class="content-title__text">Личный кабинет - Мои питомцы</span>
    </div>
    <h1 class="content-title__title">Мои питомцы</h1>
    <div class="m-sub-menu">
        <button class="m-sub-menu__btn">Все разделы</button>
    </div>
</div>
<section class="list-cards">
    <div class="list-cards__btn-add">
        <a class="btn__min-yellow" href="{% url 'lk:client_pet_create' %}">Добавить питомца</a>
    </div>
    {% if pets_list %}
    {% for pet in pets_list %}
    <div class="list-cards__item">
        <div class="list-cards__col-1">
            <div class="list-cards__row">
                <div class="key">
                    <span>Питомец:</span>
                </div>
                <div class="value">
                    <span>{{ pet.kind.value }}</span>
                </div>
            </div>
            <div class="list-cards__row">
                <div class="key">
                    <span>Кличка:</span>
                </div>
                <div class="value">
                    <span>{{ pet.name }}</span>
                </div>
            </div>
            <div class="list-cards__row">
                <div class="key">
                    <span>Пол:</span>
                </div>
                <div class="value">
                    {% if pet.sex == True %}
                    <span>Мужской</span>
                    {% else %}
                    <span>Женский</span>
                    {% endif %}
                </div>
            </div>
            <div class="list-cards__row">
                <div class="key">
                    <span>Дата рождения:</span>
                </div>
                <div class="value">
                    <span>{{ pet.date_of_birth }}</span>
                </div>
            </div>
        </div>
        <div class="list-cards__col-2">
            <div class="list-cards__avatar">
                {% if pet.photo %}
                <img src="{{pet.photo.url}}" alt="">
                {% else %}
                <svg>
                    <use href="{% static '' %}images/icons.svg#i-foot" style="color: white;"></use>
                </svg>
                {% endif %}
            </div>
        </div>
        <div class="list-cards__btns">
            <a class="btn__min-yellow" href="{% url 'lk:client_history' pet.id %}">История</a>
            <a class="btn__min-orange" href="{% url 'lk:client_pet_edit' pet.id %}">Редактировать</a>
        </div>
    </div>
    {% endfor %}
    {% endif %}
</section>
{% endblock %}