vet_clinic_backend/apps/lk/urls.py
from django.urls import path

from . import views

app_name = 'lk'

urlpatterns = [
    path('', views.client_visits, name = 'client_visits'),
    path('visit/<int:id_visit>/', views.client_visit_card, name = 'client_visit_card'),
    path('visit/<int:id_visit>/edit', views.client_visit_card_edit, name = 'client_visit_card_edit'),
    path('pets/new', views.client_pet_create, name = 'client_pet_create'),
    path('pets/', views.client_pets, name = 'client_pets'),
    path('pets/<int:id_pet>/edit/', views.client_pet_edit, name = 'client_pet_edit'),
    path('profile/', views.client_profile, name = 'client_profile'),
    path('history/<int:id_pet>/', views.client_history, name = 'client_history'),
]

vet_clinic_backend/apps/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name = 'index'),
    # path('<str:category>/', views.client_category, name = 'client_category'),
    # path('<int:id_direction>/<int:id>/', views.client_detail, name = 'client_detail'),
    # path('adm', views.index, name = 'index'),
    # path('adm/new_service', views.create, name = 'create'),
    # path('adm/<int:id_direction>/', views.category, name = 'category'),
    # path('adm/<int:id_direction>/<int:id>/', views.detail, name = 'detail'),
]

vet_clinic_backend/apps/sales/urls.py
from django.urls import path

from . import views

app_name = 'sales'

urlpatterns = [
    path('', views.client_list, name = 'client_list'),
    path('<int:id_sale>/', views.client_sale, name = 'client_sale'),
    # path('<str:category>/', views.client_category, name = 'client_category'),
    # path('adm', views.index, name = 'index'),
    # path('adm/new_service', views.create, name = 'create'),
    # path('adm/<int:id_direction>/', views.category, name = 'category'),
    # path('adm/<int:id_direction>/<int:id>/', views.detail, name = 'detail'),
]

vet_clinic_backend/apps/services/urls.py
from django.urls import path

from . import views

app_name = 'services'

urlpatterns = [
    path('', views.client_list, name = 'client_list'),
    path('<int:id_direction>/', views.client_category, name = 'client_category'),
    path('<int:id_direction>/<int:id>/', views.client_detail, name = 'client_detail'),
    path('adm', views.index, name = 'index'),
    path('adm/new_service', views.create, name = 'create'),
    path('adm/<int:id_direction>/', views.category, name = 'category'),
    path('adm/<int:id_direction>/<int:id>/', views.detail, name = 'detail'),
]

vet_clinic_backend/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from users import views as user_views

urlpatterns = [
    path('visits/', include('visits.urls')),
    path('clients/', include('clients.urls')),
    path('filials/', include('filials.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('lk/', include('lk.urls')),
    path('register/', user_views.register, name='register'),
    path('', include('main.urls')),
    path('sales/', include('sales.urls')),
    path('reviews/', include('reviews.urls')),
    path('workers/', include('workers.urls')),
    path('services/', include('services.urls')),
    path('admin/', admin.site.urls)
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

vet_clinic_backend/apps/lk/models.py
from django.db import models

vet_clinic_backend/apps/main/models.py
from django.db import models

# Create your models here.

vet_clinic_backend/apps/users/models.py
from django.db import models

# Create your models here.

vet_clinic_backend/apps/lk/forms.py
from django import forms
# from django.core.exceptions import ValidationError
from clients.models import Pet
from visits.models import Visit

class PetForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = ['name', 'kind', 'date_of_birth']

        widgets = {
            'name': forms.TextInput(),
            'kind':forms.Select(),
            'date_of_birth':forms.DateInput()

        }

class ClientForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = ['name', 'kind', 'date_of_birth']

        widgets = {
            'name': forms.TextInput(),
            'kind':forms.Select(),
            'date_of_birth':forms.DateInput()

        }

class DocCommentForm(forms.ModelForm):
    class Meta:
        model = Visit
        fields = ['comment']

        widgets = {
            'comment': forms.Textarea(attrs={'rows':10, 'style':"width:100%"})
        }

vet_clinic_backend/apps/services/forms.py
from django import forms

from .models import *

class ServiceForm(forms.ModelForm):

    class Meta:
        model = Service
        fields = ('name','description')

vet_clinic_backend/apps/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    # email = forms.EmailField()

    class Meta:
        model = User
        # fields = ['username', 'email', 'password1', 'password2']
        fields = ['username', 'password1', 'password2']

vet_clinic_backend/apps/clients/views.py
from django.http import HttpResponseRedirect
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from .models import *
from visits.models import Visit
from django.contrib.auth.models import User
from django.core.paginator import Paginator

def adm_list(request):
    if request.user.is_authenticated:
        if not request.user.groups.filter(name='managers').exists():
            raise PermissionDenied

    else:
        return HttpResponseRedirect('/accounts/login')
    clients = Client.objects.all().order_by('id')
    pets_all = Pet.objects.filter(date_of_delete = None)
    visits_all = Visit.objects.all()
    paginator = Paginator(clients, 4)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        clients_all = paginator.page(page)
    except(EmptyPage, InvalidPage):
        clients_all = paginator.page(paginator.num_pages)



    return render(request, 'clients/adm-clients.html', {'clients_all':clients_all, 'pets_all':pets_all, 'visits_all':visits_all})


    

vet_clinic_backend/apps/filials/views.py
from django.shortcuts import render, redirect
from reviews.forms import FeedbackForm

def client_contacts(request):
    if request.method == "POST":
        form = FeedbackForm(request.POST)
        if form.is_valid():
            new_review = form.save()
            return redirect('filials:client_message')
        else:
            return render(request, 'filials/contacts.html', {'form':form})
    else:
        form = FeedbackForm()

    return render(request, 'filials/contacts.html', {'form':form})

def client_message(request):
    return render(request, 'filials/success_message.html', {})

vet_clinic_backend/apps/lk/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.db.models import Q
import datetime
from django.utils import timezone
from django.utils.timezone import utc

from .forms import PetForm, DocCommentForm

from django.core.exceptions import PermissionDenied

from django.contrib.auth.models import User

from clients.models import *
from visits.models import Visit
from workers.models import Worker
from services.models import Service
from filials.models import *


from django.core.serializers.json import DjangoJSONEncoder

import datetime
import time
from datetime import timedelta


def client_visits(request):
    lk = ''
    if request.user.is_authenticated:
        try: 
            worker = Worker.objects.get(user=request.user)
            lk = 'worker'
        except:
            try: 
                client = Client.objects.get(user=request.user)
                lk = 'client'
            except:
                return HttpResponseRedirect('/accounts/login')
    else:
        return HttpResponseRedirect('/accounts/login')
    
    if lk == 'client':
        visits_all = Visit.objects.filter(client__id=client.id).order_by('-date')
        visits_active = visits_all.filter(date__gte=datetime.date.today(), date_of_delete=None)
        visits_history_all = []
        for visit in visits_all:
            if visit not in visits_active:
                visits_history_all.append(visit)
        #Фильтры
        doctors_filter = []
        service_filter = []
        for visit in visits_history_all:
            if visit.doctor not in doctors_filter:
                doctors_filter.append(visit.doctor)

            if visit.services != None:
                for service in visit.services.all():
                    if service not in service_filter:
                        service_filter.append(service)

            if visit.sale != None:
                for service in visit.sale.services.all():
                    if service not in service_filter:
                        service_filter.append(service)
        pets_filter = Pet.objects.filter(client=client)
        #Обработка фильтров
        visits_history_view = []
        search_query = request.GET.get('doctor' )
        if search_query:
            d_f,s_f,p_f,date_from,date_before = 'Все','Все','Все','',''
            visits_history_filter = []
            if request.GET['doctor'] != 'Все':
                d_f = int(request.GET['doctor'])
            if request.GET['service'] != 'Все':
                s_f = int(request.GET['service'])         
            if request.GET['pet'] != 'Все':
                p_f = int(request.GET['pet'])
            if request.GET['date_from'] != '':
                date_from = request.GET['date_from']
            if request.GET['date_before'] != '':
                date_before = request.GET['date_before']

            if d_f != 'Все' and s_f == 'Все' and p_f == 'Все':
                for visit in visits_history_all:
                    if visit.doctor.id == int(d_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit)
            
            elif d_f != 'Все' and s_f == 'Все' and p_f != 'Все':   
                for visit in visits_history_all:
                    if visit.doctor.id == int(d_f) and visit.pet.id == int(p_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit) 
            
            elif d_f != 'Все' and s_f != 'Все' and p_f != 'Все': 
                service = Service.objects.get(id=int(s_f))
                for visit in visits_history_all:
                    if service in visit.services.all() and visit.doctor.id == int(d_f) and visit.pet.id == int(p_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit)
                    if visit.sale:
                        sale = visit.sale
                        for service_in_sale in sale.services.all():
                            if service == service_in_sale and visit.doctor.id == int(d_f) and visit.pet.id == int(p_f) and visit not in visits_history_filter:
                                visits_history_filter.append(visit)
            
            elif d_f != 'Все' and s_f != 'Все' and p_f == 'Все':
                service = Service.objects.get(id=int(s_f))
                for visit in visits_history_all:
                    if service in visit.services.all() and visit.doctor.id == int(d_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit)
                    if visit.sale:
                        sale = visit.sale
                        for service_in_sale in sale.services.all():
                            if service == service_in_sale and visit.doctor.id == int(d_f) and visit not in visits_history_filter:
                                visits_history_filter.append(visit)

            elif d_f == 'Все' and s_f != 'Все' and p_f != 'Все':
                service = Service.objects.get(id=int(s_f))
                for visit in visits_history_all:
                    if service in visit.services.all() and visit.pet.id == int(p_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit)
                    if visit.sale:
                        sale = visit.sale
                        for service_in_sale in sale.services.all():
                            if service == service_in_sale and visit.pet.id == int(p_f) and visit not in visits_history_filter:
                                visits_history_filter.append(visit)

            elif d_f == 'Все' and s_f != 'Все' and p_f == 'Все':
                service = Service.objects.get(id=int(s_f))
                for visit in visits_history_all:
                    if service in visit.services.all() and visit not in visits_history_filter:
                        visits_history_filter.append(visit)
                    if visit.sale:
                        sale = visit.sale
                        for service_in_sale in sale.services.all():
                            if service == service_in_sale and visit not in visits_history_filter:
                                visits_history_filter.append(visit)

            elif d_f == 'Все' and s_f == 'Все' and p_f != 'Все':
                for visit in visits_history_all:
                    if visit.pet.id == int(p_f) and visit not in visits_history_filter:
                        visits_history_filter.append(visit)

            elif d_f == 'Все' and s_f == 'Все' and p_f == 'Все':
                visits_history_filter = visits_history_all

            for visit in visits_history_filter:
                date1 = visit.date
                if date_from != '' and date_before == '':
                    date2 = datetime.datetime.strptime(date_from, '%Y-%m-%d').replace(tzinfo=utc)
                    if date1 >= date2:
                        visits_history_view.append(visit)

                if date_from != '' and date_before != '':
                    date2 = datetime.datetime.strptime(date_from, '%Y-%m-%d').replace(tzinfo=utc)
                    date3 = datetime.datetime.strptime(date_before, '%Y-%m-%d').replace(tzinfo=utc)
                    if date1 >= date2 and date1 <= date3:
                        visits_history_view.append(visit)

                if date_from == '' and date_before != '':
                    date3 = datetime.datetime.strptime(date_before, '%Y-%m-%d').replace(tzinfo=utc) 
                    if date1 <= date3:
                        visits_history_view.append(visit)

                if date_from == '' and date_before == '':
                    visits_history_view.append(visit)
        else:
            d_f,s_f,p_f,date_from,date_before = 'Все','Все','Все','',''
            visits_history_view = visits_history_all
        #Пагинация
        paginator = Paginator(visits_history_view, 4)
        try:
            page = int(request.GET.get('page', '1'))
        except:
            page = 1
        try:
            visits_history = paginator.page(page)
        except(EmptyPage, InvalidPage):
            visits_history = paginator.page(paginator.num_pages)
        return render(request, 'lk/lk-visits.html', {'visits_all':visits_all, 'client':client, 'visits_active':visits_active, 'visits_history':visits_history, 'doctors_filter':doctors_filter, 'service_filter':service_filter, 'pets_filter':pets_filter, 'd_f':d_f, 's_f':s_f, 'p_f':p_f, 'date_from':date_from ,'date_before':date_before})
    elif lk == 'worker':
        visits_all = Visit.objects.filter(doctor=worker, date_of_delete=None)
        services_all = []
        clients_all = []
        for visit in visits_all:
            if visit.services != None:
                for service in visit.services.all():
                    if service not in services_all:
                        services_all.append(service)

            if visit.sale != None:
                for service in visit.sale.services.all():
                    if service not in services_all:
                        services_all.append(service)
            
            if visit.client != None and visit.client not in clients_all:
                clients_all.append(visit.client)

        visits_planer = []
        
        data = '['
        visits = list(visits_all)
        for visit in visits_all:
            serv = ''
            for service in visit.services.all():
                serv += str(service.name) + ', '

            data += '{"id":' + str(visit.id) + ','
            data += '"name":"' + serv + '",'
            data += '"from":' + str(time.mktime(visit.date.timetuple()) * 1000) + ','
            data += '"duration":' + str(visit.duration)
            if visits.index(visit) + 1 ==  len(visits_all):

                data += '}'
            else:
                data += '},'
        data += ']'

vet_clinic_backend/apps/main/views.py
# from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from services.models import Direction
from sales.models import Sale
from workers.models import Worker
def index(request):
    direction_list = Direction.objects.filter(date_of_delete=None)[:10]
    sale_list = Sale.objects.filter(date_of_delete=None).filter(visibility=True)[:10]
    doctors_list = Worker.objects.filter(date_of_delete=None).filter(visibility=True)[:10]

    return render(request, 'main/index.html', {'direction_list':direction_list, 'sale_list':sale_list, 'doctors_list':doctors_list})

vet_clinic_backend/templates/services/adm-services.html
{% extends 'base-adm.html' %}

{% load static %}

{% block title %}Услуги{% endblock %}

{% block sub-menu__title%}
    <h2>Направления</h2>
    <a href="adm-direction-card.html" class="sub-menu__plus">
        <svg>
            <use href="{% static '' %}images/icons.svg#i-plus"></use>
        </svg>
    </a>
{% endblock %}

{% block left-menu %}
    {% if direction_active == 0 %}
    <a href="{% url 'services:index' %}" class="sub-menu__link">
        <span class="sub-menu__active">Все ({{services_amount}})</span>
        <svg class="sub-menu__img sub-menu__active">
            <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
        </svg>
    </a>
    {% else %}
    <a href="{% url 'services:index' %}" class="sub-menu__link">
        <span>Все ({{services_amount}})</span>
        <svg class="sub-menu__img">
            <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
        </svg>
    </a>
    {% endif %}
    {% if directions_list %}
        {% for direction in directions_list %}
            <div class="row-menu">
                <a href="" class="svg-edit">
                    <svg>
                        <use href="{% static '' %}images/icons.svg#i-edit"></use>
                    </svg>
                </a>
                <a href="{% url 'services:category' direction.id %}" class="sub-menu__link">
                    {% if direction == direction_active %}
                        <span class="sub-menu__active">{{ direction.name }} ({{ direction.services.count }})</span>
                        <svg class="sub-menu__img sub-menu__active">
                            <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
                        </svg>
                    {% else %}
                        <span>{{ direction.name }} ({{ direction.services.count }})</span>
                        <svg class="sub-menu__img">
                            <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
                        </svg>
                    {% endif %}
                </a>
            </div>
        {% endfor %}
    {% else %} направления не найдены
    {% endif %}
{% endblock %}

{% block content %}
<div class="content-title adm">
        <div class="content-title__crumbs">
            {% if direction_active == 0%}
                <a href="{% url 'services:index' %}" class="content-title__link">
                    <span>Услуги - Все</span>
                </a>
            {% else %}
                <a href="{% url 'services:category' direction_active.id %}" class="content-title__link">
                    <span>Услуги - {{direction_active.name}}</span>
                </a>
            {% endif %}
        </div>
        <h1 class="content-title__title">Услуги</h1>
        <div class="m-sub-menu">
            <button class="m-sub-menu__btn">Все направления</button>
        </div>
    </div>
    <section class="search-sorting">
        <form class="search">
            <div class="search__img">
                <label class="search__label" for="search">
                    <svg>
                        <use href="{% static '' %}images/icons.svg#i-search"></use>
                    </svg>
                </label>
            </div>
            <input id="search" class="search__input" type="text" placeholder="найти услугу">
            <button class="search__button">
                <svg class="search__button">
                    <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
                </svg>
            </button>
        </form>
        <div class="search-sorting__sort">
            <input type="radio" name="sort" id="id">
            <label for="id">ID</label>
            <input type="radio" name="sort" id="fio">
            <label for="fio">Цена</label>
            <svg>
                <use href="{% static '' %}images/icons.svg#i-bottom-arrow"></use>
            </svg>
        </div>
        <div class="search-sorting__btn">
            <a href="{% url 'services:create' %}" class="btn__min-orange">Добавить услугу</a>
        </div>
    </section>
    <section class="list">
        {% if services_list %}
            {% for service in services_list.object_list %}
                {% if direction_active == 0 %}
                    <a href="{% url 'services:detail' direction_active service.id %}" class="list__item">
                        <div class="list__description">
                            <div class="list__id">
                                <span class="id">{{ service.id }}</span>
                                <span class="name">{{ service.name }}</span>
                            </div>
                        </div>
                        <div class="list__cost">
                            <span>{{ service.cost }} pуб.</span>
                        </div>
                    </a>
                {% else %}
                    <a href="{% url 'services:detail' direction_active.id service.id %}" class="list__item">
                        <div class="list__description">
                            <div class="list__id">
                                <span class="id">{{ service.id }}</span>
                                <span class="name">{{ service.name }}</span>
                            </div>
                        </div>
                        <div class="list__cost">
                            <span>{{ service.cost }} pуб.</span>
                        </div>
                    </a>
                {% endif %}
            {% endfor %}
        {% else %} услуги не найдены
        {% endif %}
    </section>
    <section class="pagination">
        {% if services_list.has_previous %}
            <a href="?page={{ services_list.previous_page_number }}">«</a>
        {% endif %}
        {% for pg in services_list.paginator.page_range %}
            {% if services_list.number == pg %}
                <a href="?page={{ pg }}" class="pagination__active">{{ pg }}</a>
            {% else %}
                <a href="?page={{ pg }}">{{ pg }}</a>
            {% endif %}
        {% endfor %}
        {% if services_list.has_next %}
            <a href="?page={{ services_list.next_page_number }}">»</a>
        {% endif %}
    </section>

{% endblock %}

vet_clinic_backend/templates/services/services.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Услуги{% endblock %}

{% block sub-menu__title%}
    <h2>Направления</h2>
{% endblock %}

{% block left-menu %}
    {% if direction_active == 0 %}
        <a href="{% url 'services:client_list' %}" class="sub-menu__link">
            <span class="sub-menu__active">Все ({{services_amount}})</span>
            <svg class="sub-menu__img sub-menu__active">
                <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
            </svg>
        </a>
    {% else %}
        <a href="{% url 'services:client_list' %}" class="sub-menu__link">
            <span>Все ({{services_amount}})</span>
            <svg class="sub-menu__img">
                <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
            </svg>
        </a>
    {% endif %}
    {% if directions_list %}
        {% for direction in directions_list %}
            <a href="{% url 'services:client_category' direction.id %}" class="sub-menu__link">
                {% if direction == direction_active %}
                    <span class="sub-menu__active">{{ direction.name }} ({{ direction.services.count }})</span>
                    <svg class="sub-menu__img sub-menu__active">
                            <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
                    </svg>
                {% else %}
                    <span>{{ direction.name }} ({{ direction.services.count }})</span>
                    <svg class="sub-menu__img">
                            <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
                    </svg>
                {% endif %}
            </a>
        {% endfor %}
    {% else %} направления не найдены
    {% endif %}
{% endblock %}

{% block content %}
<div class="content-title adm">
        <div class="content-title__crumbs">
            <a href="index.html" class="content-title__link">
                <span>Главная</span>
            </a>
            <svg class="content-title__img">
                <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
            </svg>
            {% if direction_active == 0%}
                <span class="content-title__text">Услуги - Все</span>
            {% else %}
                <span class="content-title__text">Услуги - {{direction_active.name}}</span>
            {% endif %}
        </div>
        <h1 class="content-title__title">Услуги</h1>
        <div class="m-sub-menu">
            <button class="m-sub-menu__btn">Все направления</button>
        </div>
    </div>
    <section class="search-row">
        <form class="search" style="width: 100%;" action="{% url 'services:client_list' %}">
            <div class="search__img">
                <label class="search__label" for="search">
                    <svg>
                        <use href="{% static '' %}images/icons.svg#i-search"></use>
                    </svg>
                </label>
            </div>
            <input name="search" id="search" class="search__input" type="text" placeholder="найти услугу">
            <button type="submit" class="search__button">
                <svg class="search__button">
                    <use href="{% static '' %}images/icons.svg#i-right-arrow"></use>
                </svg>
            </button>
        </form>
    </section>
    <section class="list">
        {% if services_list %}
            {% for service in services_list.object_list %}
                {% if direction_active == 0 %}
                    <a href="{% url 'services:client_detail' direction_active service.id %}" class="list__item">
                        <div class="list__description">
                            <div class="list__id">
                                <span class="id">{{ service.id }}</span>
                                <span class="name">{{ service.name }}</span>
                            </div>
                        </div>
                        <div class="list__cost">
                            <span>{{ service.cost }} pуб.</span>
                        </div>
                    </a>
                {% else %}
                    <a href="{% url 'services:client_detail' direction_active.id service.id %}" class="list__item">
                        <div class="list__description">
                            <div class="list__id">
                                <span class="id">{{ service.id }}</span>
                                <span class="name">{{ service.name }}</span>
                            </div>
                        </div>
                        <div class="list__cost">
                            <span>{{ service.cost }} pуб.</span>
                        </div>
                    </a>
                {% endif %}
            {% endfor %}
        {% else %} услуги не найдены
        {% endif %}
    </section>
    <section class="pagination">
        {% if services_list.has_previous %}
            <a href="?page={{ services_list.previous_page_number }}">«</a>
        {% endif %}
        {% for pg in services_list.paginator.page_range %}
            {% if services_list.number == pg %}
                <a href="?page={{ pg }}" class="pagination__active">{{ pg }}</a>
            {% else %}
                <a href="?page={{ pg }}">{{ pg }}</a>
            {% endif %}
        {% endfor %}
        {% if services_list.has_next %}
            <a href="?page={{ services_list.next_page_number }}">»</a>
        {% endif %}
    </section>

{% endblock %}